version: 2.1

executors:
  node-project:
    working_directory: ~/project
    docker:
      - image: cimg/node:22.21.1

jobs:
  build:
    executor: node-project
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Build Site
          command: npm run build
      - store_artifacts:
          path: dist
      - save_cache:
          key: deploy-cache-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - ~/project/dist
            - ~/project/firebase.json
            - ~/project/.firebaserc
            - ~/project/package-lock.json

  deploy:
    executor: node-project
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: deploy-cache-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build
